# Generated by Django 5.2.17 on 2026-09-08 19:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DateRule",
            fields=[
                ("id", models.SlugField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=200)),
                ("published_range_low_days", models.PositiveSmallIntegerField()),
                ("published_range_high_days", models.PositiveSmallIntegerField()),
                ("initial_reminder_days", models.PositiveSmallIntegerField()),
                (
                    "anchor_kind",
                    models.CharField(
                        choices=[
                            ("purchase", "purchase"),
                            ("opening", "opening"),
                            ("cooking", "cooking"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "storage_condition",
                    models.CharField(
                        choices=[("refrigerator", "refrigerator")],
                        default="refrigerator",
                        max_length=20,
                    ),
                ),
                ("applies_to", models.JSONField(default=list)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("initial_reminder_days__gte", 1),
                            (
                                "published_range_high_days__gte",
                                models.F("published_range_low_days"),
                            ),
                        ),
                        name="date_rule_range_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator("^[a-z0-9-]+$")
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("aliases", models.JSONField(blank=True, default=list)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("produce", "produce"),
                            ("dairy", "dairy"),
                            ("meat", "meat"),
                            ("pantry", "pantry"),
                            ("spice", "spice"),
                            ("frozen", "frozen"),
                        ],
                        max_length=20,
                    ),
                ),
                ("default_units", models.JSONField(default=list)),
                (
                    "form",
                    models.CharField(
                        choices=[("raw", "raw"), ("cooked", "cooked"), ("na", "na")],
                        default="na",
                        max_length=10,
                    ),
                ),
                ("is_custom", models.BooleanField(default=False)),
                ("dietary_flags", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("is_custom", False)),
                        name="reference_food_not_custom",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("source_name", models.CharField(max_length=100)),
                ("source_url", models.URLField(max_length=500)),
                (
                    "cuisine",
                    models.CharField(
                        choices=[
                            ("american", "american"),
                            ("korean", "korean"),
                            ("indian", "indian"),
                            ("brazilian", "brazilian"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meal_types", models.JSONField(default=list)),
                ("is_side", models.BooleanField(default=False)),
                (
                    "yield_servings",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("999999.999999")
                            ),
                        ],
                    ),
                ),
                (
                    "total_time_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("vegetarian_verified", models.BooleanField(blank=True, null=True)),
                ("retrieved_on", models.DateField()),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("yield_servings__gt", 0)),
                        name="recipe_positive_yield",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceReference",
            fields=[
                (
                    "id",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("merchant", models.CharField(max_length=100)),
                (
                    "shopping_method",
                    models.CharField(
                        choices=[
                            ("pickup", "pickup"),
                            ("online_delivery", "online_delivery"),
                            ("online_shipping", "online_shipping"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location_verified", models.BooleanField(default=False)),
                ("location_label", models.CharField(blank=True, max_length=250)),
                (
                    "package_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("999999.999999")
                            ),
                        ],
                    ),
                ),
                (
                    "package_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("g", "g"),
                            ("kg", "kg"),
                            ("oz", "oz"),
                            ("lb", "lb"),
                            ("ml", "ml"),
                            ("L", "L"),
                            ("fl oz", "fl oz"),
                            ("cup", "cup"),
                            ("tbsp", "tbsp"),
                            ("tsp", "tsp"),
                            ("item", "item"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "price_cents",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "observed_promotional_price_cents",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "observed_initial_range_cents",
                    models.JSONField(blank=True, null=True),
                ),
                ("source_url", models.URLField(max_length=500)),
                ("observed_page_url", models.URLField(max_length=500)),
                ("observed_on", models.DateField()),
                ("automatic_estimate_eligible", models.BooleanField(default=False)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.food"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price_cents__gt", 0)),
                        name="price_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("automatic_estimate_eligible", False),
                            models.Q(
                                ("package_quantity__gt", 0),
                                ("package_quantity__isnull", False),
                                ("package_unit__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="eligible_price_package_known",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("999999.999999")
                            ),
                        ],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("g", "g"),
                            ("kg", "kg"),
                            ("oz", "oz"),
                            ("lb", "lb"),
                            ("ml", "ml"),
                            ("L", "L"),
                            ("fl oz", "fl oz"),
                            ("cup", "cup"),
                            ("tbsp", "tbsp"),
                            ("tsp", "tsp"),
                            ("item", "item"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("optional", models.BooleanField(default=False)),
                ("to_taste", models.BooleanField(default=False)),
                ("preparation", models.CharField(blank=True, max_length=1000)),
                ("source_text", models.CharField(max_length=1000)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.food"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="catalog.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipe", "food", "preparation"),
                        name="unique_recipe_ingredient",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("to_taste", False),
                            ("amount__isnull", True),
                            _connector="OR",
                        ),
                        name="to_taste_no_amount",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount__isnull", True),
                            models.Q(("amount__gt", 0), ("unit__isnull", False)),
                            _connector="OR",
                        ),
                        name="ingredient_quantity_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SamplePantrySeed",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("999999.999999")
                            ),
                        ],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "g"),
                            ("kg", "kg"),
                            ("oz", "oz"),
                            ("lb", "lb"),
                            ("ml", "ml"),
                            ("L", "L"),
                            ("fl oz", "fl oz"),
                            ("cup", "cup"),
                            ("tbsp", "tbsp"),
                            ("tsp", "tsp"),
                            ("item", "item"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        choices=[
                            ("refrigerator", "refrigerator"),
                            ("freezer", "freezer"),
                            ("pantry", "pantry"),
                            ("counter", "counter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "date_kind",
                    models.CharField(
                        choices=[
                            ("label", "label"),
                            ("user", "user"),
                            ("estimate", "estimate"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.food"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="sample_quantity_positive",
                    )
                ],
            },
        ),
    ]
