# Generated by Django 5.2.17 on 2026-09-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplepantryseed",
            name="date_kind",
            field=models.CharField(
                choices=[
                    ("label", "label"),
                    ("user", "user"),
                    ("estimate", "estimate"),
                    ("unknown", "unknown"),
                ],
                max_length=10,
            ),
        ),
    ]
