# Generated by Django 5.2.17 on 2026-09-08 20:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("produce", "produce"),
                            ("dairy", "dairy"),
                            ("meat", "meat"),
                            ("pantry", "pantry"),
                            ("spice", "spice"),
                            ("frozen", "frozen"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[("raw", "raw"), ("cooked", "cooked"), ("na", "na")],
                        default="na",
                        max_length=10,
                    ),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PantryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(
                                Decimal("999999.999999")
                            ),
                        ],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "g"),
                            ("kg", "kg"),
                            ("oz", "oz"),
                            ("lb", "lb"),
                            ("ml", "ml"),
                            ("L", "L"),
                            ("fl oz", "fl oz"),
                            ("cup", "cup"),
                            ("tbsp", "tbsp"),
                            ("tsp", "tsp"),
                            ("item", "item"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        choices=[
                            ("refrigerator", "refrigerator"),
                            ("freezer", "freezer"),
                            ("pantry", "pantry"),
                            ("counter", "counter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "date_kind",
                    models.CharField(
                        choices=[
                            ("label", "label"),
                            ("user", "user"),
                            ("estimate", "estimate"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("anchor_date", models.DateField(blank=True, null=True)),
                (
                    "anchor_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("purchase", "purchase"),
                            ("opening", "opening"),
                            ("cooking", "cooking"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pantry.customfood",
                    ),
                ),
                (
                    "estimate_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.daterule",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.food",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "food"], name="pantry_owner_food_idx"
                    ),
                    models.Index(
                        fields=["owner", "date"], name="pantry_owner_date_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("custom_food__isnull", True), ("food__isnull", False)
                            ),
                            models.Q(
                                ("custom_food__isnull", False), ("food__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="pantry_exactly_one_food",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quantity__gte", 0),
                            ("quantity__lte", Decimal("999999.999999")),
                        ),
                        name="pantry_quantity_bounds",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "unit__in",
                                [
                                    "g",
                                    "kg",
                                    "oz",
                                    "lb",
                                    "ml",
                                    "L",
                                    "fl oz",
                                    "cup",
                                    "tbsp",
                                    "tsp",
                                    "item",
                                ],
                            )
                        ),
                        name="pantry_known_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "storage_location__in",
                                ["refrigerator", "freezer", "pantry", "counter"],
                            )
                        ),
                        name="pantry_known_storage",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("date_kind__in", ["label", "user", "estimate"])
                        ),
                        name="pantry_known_date_kind",
                    ),
                ],
            },
        ),
    ]
