# Generated by Django 5.2.17 on 2026-09-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pantry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pantryitem",
            name="anchor_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("purchase", "purchase"),
                    ("opening", "opening"),
                    ("cooking", "cooking"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
