# Generated by Django 5.2.17 on 2026-09-08 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("pantry", "0002_alter_pantryitem_anchor_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CookingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_snapshot", models.CharField(max_length=250)),
                ("servings", models.PositiveSmallIntegerField()),
                ("cooked_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("idempotency_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("response_snapshot", models.JSONField(default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CookingLogLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_id_snapshot", models.CharField(max_length=200)),
                ("review", models.JSONField(default=dict)),
                (
                    "cooking_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pantry.cookinglog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_snapshot", models.JSONField(default=dict)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=12)),
                ("unit", models.CharField(max_length=10)),
                (
                    "kind",
                    models.CharField(
                        choices=[("used", "used"), ("discarded", "discarded")],
                        max_length=10,
                    ),
                ),
                ("source_action", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("undo_expires_at", models.DateTimeField(null=True)),
                (
                    "cooking_log",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pantry.cookinglog",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pantry_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pantry.pantryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PantryCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("whole", "whole"), ("selected", "selected")],
                        max_length=10,
                    ),
                ),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("items", models.ManyToManyField(blank=True, to="pantry.pantryitem")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SavedPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_filters", models.JSONField(default=dict)),
                ("theme", models.CharField(default="system", max_length=10)),
                ("last_filter", models.JSONField(default=dict)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="cookinglog",
            index=models.Index(
                fields=["owner", "-created_at"], name="cooking_owner_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="cookinglog",
            constraint=models.UniqueConstraint(
                fields=("owner", "idempotency_key"), name="cooking_owner_key"
            ),
        ),
        migrations.AddIndex(
            model_name="historyentry",
            index=models.Index(
                fields=["owner", "-created_at"], name="history_owner_created"
            ),
        ),
    ]
