# Generated by Django 5.2.17 on 2026-09-09 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_samplepantryseed_date_kind"),
        ("pantry", "0003_cookinglog_cookinglogline_historyentry_pantrycheck_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pantryitem",
            name="pantry_known_date_kind",
        ),
        migrations.AlterField(
            model_name="pantryitem",
            name="date_kind",
            field=models.CharField(
                choices=[
                    ("label", "label"),
                    ("user", "user"),
                    ("estimate", "estimate"),
                    ("unknown", "unknown"),
                ],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="pantryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("date_kind__in", ["label", "user", "estimate", "unknown"])
                ),
                name="pantry_known_date_kind",
            ),
        ),
    ]
