# Generated by Django 5.2.17 on 2026-09-09 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pantry", "0004_remove_pantryitem_pantry_known_date_kind_and_more"),
        ("recipes", "0002_alter_favorite_curated_recipe_personalrecipe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookinglog",
            name="personal_recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipes.personalrecipe",
            ),
        ),
    ]
