# Generated by Django 5.2.17 on 2026-09-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_demostate"),
    ]

    operations = [
        migrations.AddField(
            model_name="demostate",
            name="ingredient_batches",
            field=models.JSONField(default=dict),
        ),
    ]
