# Generated by Django 5.2.17 on 2026-09-09 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_samplepantryseed_date_kind"),
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="curated_recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.recipe",
            ),
        ),
        migrations.CreateModel(
            name="PersonalRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("instructions", models.TextField(blank=True)),
                ("servings", models.PositiveSmallIntegerField(default=2)),
                ("total_time_minutes", models.PositiveIntegerField(null=True)),
                ("categories", models.JSONField(default=list)),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_personal_recipe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipes.personalrecipe",
                    ),
                ),
                (
                    "source_recipe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="favorite",
            name="personal_recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.personalrecipe",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("owner", "personal_recipe"), name="favorite_owner_personal"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("curated_recipe__isnull", False),
                        ("personal_recipe__isnull", True),
                    ),
                    models.Q(
                        ("curated_recipe__isnull", True),
                        ("personal_recipe__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="favorite_exactly_one_target",
            ),
        ),
    ]
