# Generated by Django 5.2.17 on 2026-09-09 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_samplepantryseed_date_kind"),
        ("pantry", "0005_cookinglog_personal_recipe"),
        ("recipes", "0002_alter_favorite_curated_recipe_personalrecipe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalRecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=6, max_digits=12, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=10)),
                ("optional", models.BooleanField(default=False)),
                ("to_taste", models.BooleanField(default=False)),
                ("preparation", models.TextField(blank=True)),
                (
                    "custom_food",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pantry.customfood",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.food",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.personalrecipe",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("custom_food__isnull", True), ("food__isnull", False)
                            ),
                            models.Q(
                                ("custom_food__isnull", False), ("food__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="personal_ingredient_one_food",
                    )
                ],
            },
        ),
    ]
